resources:
  - name: epona-repo
    type: git
    source:
      branch: main
      uri: https://github.com/wolfson109/epona.git
  - name: epona-build-image
    type: docker-image
    source:
      repository: rhyswheater/epona-build
      username: ((dockerhub-username))
      password: ((dockerhub-password))

jobs:
- name: build-and-push-epona-build-image
  plan:
    - get: epona-repo
    - put: epona-build-image
      params:
        build: epona-repo
- name: epona-build
  plan:
  - get: epona-repo
    trigger: true
  - task: epona-build
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: rhyswheater/epona-build
      inputs:
      - name: epona-repo
      outputs:
      - name: epona-artifacts
      run:
        path: sh
        args:
        - -cx
        - |
          aws cdk synth > epona-artifacts/cloudformation.json
          cat epona-artifacts/cloudformation.json